version: '3'
services:
  worker:
    build: ./DockerFiles/Worker
    ports:
      - ${LOCAL_IP}:${MY_HAMMER_SERVER_PORT}:81
      - ${LOCAL_IP}:${PHP_SSH_PORT}:22
    depends_on:
      - redis
      - mysql
      - memcached
    links:
      - redis
      - mysql
      - memcached
    environment:
      MYHAMMER_REDIS_REV: 1
      MYHAMMER_MYSQL_HOST: mysql
      MYHAMMER_MYSQL_DATABASE: myhammer
      MYHAMMER_MYSQL_USER: root
      MYHAMMER_MYSQL_PASSWORD: root
      MYHAMMER_MYSQL_PORT: 3306
      LOCAL_DEV_DIR: ${LOCAL_DEV_DIR}
      VENDOR_DIR: ${VENDOR_DIR}
    volumes:
      - ${LOCAL_DEV_DIR}:/var/www
      - ${LOCAL_DEV_DIR}/storage:/var/www/storage
      - data_composer:/root/.composer
  redis:
    image: redis
  mysql:
    build: ./DockerFiles/Mysql
    ports:
      - ${LOCAL_IP}:${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  memcached:
    build: ./DockerFiles/Memcached
